import {
    LayoutDashboard,
    Users,
    Package,
    FileText,
    Truck,
    Settings,
    Moon,
    Sun,
    Search,
    Plus,
    X,
    AlertTriangle,
    CheckCircle,
    ChevronRight,
    Layout,
    Menu,
    Bell,
    Printer,
    Music,
    LogOut
} from 'lucide-react';

export const Icons = {
    Dashboard: LayoutDashboard,
    Clientes: Users,
    Equipamentos: Package,
    Orcamentos: FileText,
    Logistica: Truck,
    Settings: Settings,
    Sun: Sun,
    Moon: Moon,
    Search: Search,
    Add: Plus,
    Close: X,
    Warning: AlertTriangle,
    Success: CheckCircle,
    Error: AlertTriangle,
    Chevron: ChevronRight,
    Layout: Layout,
    Menu: Menu,
    Notif: Bell,
    Printer: Printer,
    Logo: Music,
    Logout: LogOut
};
